// Zone name
#define LOCALE_ZONENAME_OILSUPPLEMENTBASE "Oil Supplement Base"
#define LOCALE_ZONENAME_MANSION "Mansion"
#define LOCALE_ZONENAME_WAREHOUSE "Warehouse"

// Fight-style name
#define LOCALE_FIGHTSTYLE_NORMAL "Normal"
#define LOCALE_FIGHTSTYLE_BOXING "Boxing"
#define LOCALE_FIGHTSTYLE_KUNGFU "Kung-Fu"
#define LOCALE_FIGHTSTYLE_KNEEHEAD "Knee-Head"
#define LOCALE_FIGHTSTYLE_GRABKICK "Grab-Kick"
#define LOCALE_FIGHTSTYLE_ELBOW "Elbow"

// Message
#define LOCALE_MESSAGE_NOTAUTHORIZEDCOMMAND "You are not authorized to use this command"
#define LOCALE_MESSAGE_YOUARENOTLOGGED "You are not logged in"
#define LOCALE_MESSAGE_PLAYERSPECTINGSOMEONE "That player is spectating someone"
#define LOCALE_MESSAGE_MUSTBEONDUTY "You must be on-duty to do that"
#define LOCALE_MESSAGE_YOUMUSTBEINVEHICLE "You must be in a vehicle to do that"
#define LOCALE_MESSAGE_PLAYERNOTLOGGED "That player is not logged in yet"
#define LOCALE_MESSAGE_INVALIDPLAYER "Invalid player specified"
#define LOCALE_MESSAGE_CANNOTAFFORD "You don't have enough money to afford that"
#define LOCALE_MESSAGE_INVALIDVEHICLE "Invalid vehicle or not spawned yet"
#define LOCALE_MESSAGE_CANTDOONDUTYSTAFF "You cannot do that on staff who are on-duty"
#define LOCALE_MESSAGE_COMMANDISNOTYOURCLASS "This command is not for your class"
#define LOCALE_MESSAGE_INVALIDACCOUNT "Invalid account specified"
#define LOCALE_MESSAGE_INVALIDWEAPON "Invalid weapon specified"
#define LOCALE_MESSAGE_CANTPERFORMANIMINVEHICLE "You cannot do that whilst in a vehicle"
#define LOCALE_MESSAGE_MUSTBEOFFDUTY "You must be off-duty to do that"
#define LOCALE_MESSAGE_CANTSPEAKMUTED "You are muted and cannot speak"
#define LOCALE_MESSAGE_CANTUSECOMMANDONTHATPLAYER "You can not use this command on that player"
#define LOCALE_MESSAGE_CANTDOTHATRIGHTNOW "You can not do that right now"
#define LOCALE_MESSAGE_CANTUSECOMMANDYOURSELF "You can not use this command on yourself"
#define LOCALE_MESSAGE_NOTHINGFOUND "Nothing found"

// Help
#define LOCALE_HELP_ADMINRULES "{FFFFFF}1. Do not teleport players without a good reason.\n \
	2. /slay ing is used as a last resort, use '/respawn' primarily.\n \
	3. Abusing /announce is not allowed.\n \
	4. When dealing with players, correct grammar is required.\n \
	5. Do not abuse admin duty. Doing so will result in a demotion.\n \
	6. You are still a player, respect the server rules.\n \
	7. Do not be abusive towards players, no matter how they are towards you.\n \
	8. Destroy your spawned vehicles when finished.\n \
	9. Do not abuse /clearchat command.\n \
	10. Just VIPs can set a custom skin.\n \
	11. Spectation must not be used as an in-game advantage."
	
#define LOCALE_HELP_RADIOCODES "{FFFFFF}/r1 = Attack!\n \
	/r2 = Sniper At Base\n \
	/r3 = Roger That\n \
	/r4 = Negative\n \
	/r5 = Tank Incoming\n \
	/r6 = Missile Incoming\n \
	/r7 = Cover Me\n \
	/r8 = Area Secure\n \
	/r9 = Grenade!\n \
	/r10 = Spy In The Base"
#define LOCALE_HELP_GENERAL "{FFFFFF}This Mode is based on TEAM DEATH MATCH.\n \
	Kill as many enemies as possible to rank up.\n \
	Capture Prototypes and take it to your base.\n \
	Capture Zones to earn score/money, also for a constant income.\n \
	If you have any Question use /ask(/helpme) and ask staff for help."
#define LOCALE_HELP_RULES "{FFFFFF}Don't Use Any Kind Of Hacks/Cheats\n \
	Don't Insult/Spam/Flood/Advertise\n \
	Don't Kill People Using Heli-blade/Car Park or Car Ram\n \
	Don't Spawn Kill or Base Rape\n \
	Don't Ask For Score/Money From Admins\n \
	Don't Capture While AFK/Pausing\n \
	Don't Abuse Any Bug (C-Bug, Slide Bug etc)\n \
	Don't Provoke/Insult Players/Admins\n \
	No Score Farming and Money Farming\n \
	Don't attack your teammates\n \
	{FFFF00}Not Following These Rules Leads To Punishment"
#define LOCALE_HELP_CLASS "{009E00}Soldier {FFFFFF}- No Special Commands, Good Fight On Foot.\n \
	{009E00}Sniper {FFFFFF}- Weak Fight On Foot & Hidden On Mini-Map/Radar.\n \
	{009E00}Engineer {FFFFFF}- Good Fight On Foot & Through Vehicles.\n \
	{009E00}JetTrooper {FFFFFF}- Can Spawn Jet Pack Using /jp.\n \
	{009E00}Pilot {FFFFFF}- No Special Commands, Good Fight And Damage Through Air Vehciles.\n \
	{009E00}Support {FFFFFF}- Have Special Commands for Mates, Use /shelp For More Info.\n \
	{009E00}Spy {FFFFFF}- Can Disguise As Other Team's Use /spyhelp For More Info.\n \
	{009E00}VIP {FFFFFF}- Special Commands With Class, Use /dhelp For More Info.\n \
	{009E00}Demolisher {FFFFFF}- Have Good Weapons But Weaker Than Terminator.\n \
	{009E00}Terminator {FFFFFF}- Most Powerful Class But Has No Special Commands."
#define LOCALE_HELP_NUKE "{FFFFFF}- You need to be Rank 6 & have $200,000\n \
	- You need to Capture Area-51\n \
	- You need to pickup Skull icon in Area-51's Control Room"
